# https://lgtm.com/help/lgtm/customizing-file-classification
path_classifiers:
  plugins:
    - plugins/

extraction:
  javascript:
    # The `index` step extracts information from the files in the codebase.
    index:
      # Specify a list of files and folders to exclude from extraction.
      filters:
        - exclude: plugins/
      exclude:
        - plugins/
